// <auto-generated />
using System;
using FeniksServerSide.Class;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dbInthouseContext.Migrations
{
    [DbContext(typeof(InthouseContext))]
    [Migration("20241028094414_0.0.3")]
    partial class _003
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FeniksServerSide.Class.InthouseProp", b =>
                {
                    b.Property<int>("InHouse_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudConnection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hub_ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InHouse_app_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InHouse_ID");

                    b.ToTable("InthouseProp");
                });

            modelBuilder.Entity("FeniksServerSide.Class.Statistics", b =>
                {
                    b.Property<int>("Statistic_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TK_Inthouse_ID")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Statistic_ID");

                    b.HasIndex("TK_Inthouse_ID");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("FeniksServerSide.Class.Statistics", b =>
                {
                    b.HasOne("FeniksServerSide.Class.InthouseProp", "InthouseProp")
                        .WithMany("Statistics")
                        .HasForeignKey("TK_Inthouse_ID");

                    b.Navigation("InthouseProp");
                });

            modelBuilder.Entity("FeniksServerSide.Class.InthouseProp", b =>
                {
                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
