// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
}

declare interface Window {
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
}
export type IntHouseProp = {
    inHouse_ID: number;
    inHouse_app_id: string;
    hub_ID: string;
    name: string;
    cloudConnection: string;
    password: string;
    username: string;
    lastStatus: lastStatus;
};
type lastStatus = {
    status: string;
    response: string;
    date: string;
    time: string;
};

export type InthousePropUpdate = {
    inHouse_ID: number;
    inHouse_app_id: string;
    hub_ID: string;
    name: string;
    password: string;
    username: string;
};
export type InthousePropAdd = {
    inHouse_app_id: string;
    hub_ID: string;
    name: string;
    password: string;
    username: string;
};
